service: urlshortner

frameworkVersion: ">=1.8.0"

provider:
  name: aws
  runtime: nodejs6.10

functions:
  main:
    handler: main/index.handler
    events:
      - http:
          path: /
          method: get
  create:
    handler: create/index.handler
    events:
      - http:
          path: /
          method: post
  redirect:
    handler: redirect/index.handler
    events:
      - http:
          path: /{slug}
          method: get